/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kwin.Decoration.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KWINDECORATIONADAPTOR_H_55611149668415
#define KWINDECORATIONADAPTOR_H_55611149668415

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kwin.Decoration
 */
class DecorationAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kwin.Decoration")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kwin.Decoration\" >\n"
"    <method name=\"dcopUpdateClientList\" />\n"
"  </interface>\n"
        "")
public:
    DecorationAdaptor(QObject *parent);
    virtual ~DecorationAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void dcopUpdateClientList();
Q_SIGNALS: // SIGNALS
};

#endif
