# SPDX-FileCopyrightText: 2026 Kristen McWilliam <kristen@kde.org>
# SPDX-FileCopyrightText: 2026 Tobias Ozór <tobiasozor@outlook.com>
#
# SPDX-License-Identifier: BSD-2-Clause

# Configuration file for qmllint

[General]
# QML LSP doesn't currently work with some of our custom types and functions, 
# so disable the lint warnings for them until that is fixed.
disableUnqualifiedAccess = "i18n,i18nc,i18nd,i18ndc,i18ncp,i18np,xi18nc,xi18ndc,kcm,KWinOptionsSettings"
