# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/breeze-icons': 'Frameworks/6.24'
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kdeclarative': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'
    'frameworks/kglobalaccel': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kidletime': 'Frameworks/6.24'
    'frameworks/knewstuff': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kpackage': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/ksvg': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'libraries/libqaccessibilityclient': 'v0.6.0'
    'libraries/plasma-wayland-protocols': 'v1.20.0'
    'plasma/plasma-activities': '@same'
    'plasma/kdecoration': '@same'
    'plasma/kglobalacceld': '@same'
    'plasma/knighttime': '@same'
    'plasma/kpipewire': '@same'
    'plasma/kscreenlocker': '@same'
    'plasma/kwayland': '@same'
    'third-party/wayland': '@latest'
    'third-party/wayland-protocols': '@latest'

RuntimeDependencies:
 - 'on': ['@all']
   'require':
    'frameworks/kirigami': 'Frameworks/6.24'
    'plasma/aurorae': '@same'
    'plasma/breeze': '@same'
    'plasma/libplasma': '@same'
    'plasma/plasma-workspace': '@same' # kscreenlocker needs it

Options:
 ctest-arguments: '--repeat until-pass:3 --timeout 90'
 use-ccache: True
 cppcheck-arguments: '--enable=warning,style,performance --library=kwin-cppcheck.xml --suppress-xml=cppcheck-suppressions.xml'
 cppcheck-ignore-files:
  - autotests
 require-passing-tests-on: ['Linux/Qt6']
 run-qmllint: True
