/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kwin.Kwin.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "kwinadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KWinAdaptor
 */

KWinAdaptor::KWinAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KWinAdaptor::~KWinAdaptor()
{
    // destructor
}

void KWinAdaptor::cascadeDesktop()
{
    // handle method call org.kde.kwin.KWin.cascadeDesktop
    QMetaObject::invokeMethod(parent(), "cascadeDesktop");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->cascadeDesktop();
}

void KWinAdaptor::circulateDesktopApplications()
{
    // handle method call org.kde.kwin.KWin.circulateDesktopApplications
    QMetaObject::invokeMethod(parent(), "circulateDesktopApplications");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->circulateDesktopApplications();
}

int KWinAdaptor::currentDesktop()
{
    // handle method call org.kde.kwin.KWin.currentDesktop
    int out0;
    QMetaObject::invokeMethod(parent(), "currentDesktop", Q_RETURN_ARG(int, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->currentDesktop();
    return out0;
}

void KWinAdaptor::doNotManage(const QString &name)
{
    // handle method call org.kde.kwin.KWin.doNotManage
    QMetaObject::invokeMethod(parent(), "doNotManage", Q_ARG(QString, name));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->doNotManage(name);
}

void KWinAdaptor::killWindow()
{
    // handle method call org.kde.kwin.KWin.killWindow
    QMetaObject::invokeMethod(parent(), "killWindow");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->killWindow();
}

bool KWinAdaptor::kompmgrIsRunning()
{
    // handle method call org.kde.kwin.KWin.kompmgrIsRunning
    bool out0;
    QMetaObject::invokeMethod(parent(), "kompmgrIsRunning", Q_RETURN_ARG(bool, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->kompmgrIsRunning();
    return out0;
}

void KWinAdaptor::nextDesktop()
{
    // handle method call org.kde.kwin.KWin.nextDesktop
    QMetaObject::invokeMethod(parent(), "nextDesktop");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->nextDesktop();
}

void KWinAdaptor::previousDesktop()
{
    // handle method call org.kde.kwin.KWin.previousDesktop
    QMetaObject::invokeMethod(parent(), "previousDesktop");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->previousDesktop();
}

void KWinAdaptor::reconfigure()
{
    // handle method call org.kde.kwin.KWin.reconfigure
    QMetaObject::invokeMethod(parent(), "reconfigure");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->reconfigure();
}

void KWinAdaptor::refresh()
{
    // handle method call org.kde.kwin.KWin.refresh
    QMetaObject::invokeMethod(parent(), "refresh");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->refresh();
}

bool KWinAdaptor::setCurrentDesktop(int desktop)
{
    // handle method call org.kde.kwin.KWin.setCurrentDesktop
    bool out0;
    QMetaObject::invokeMethod(parent(), "setCurrentDesktop", Q_RETURN_ARG(bool, out0), Q_ARG(int, desktop));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->setCurrentDesktop(desktop);
    return out0;
}

void KWinAdaptor::setDesktopLayout(int orientation, int x, int y)
{
    // handle method call org.kde.kwin.KWin.setDesktopLayout
    QMetaObject::invokeMethod(parent(), "setDesktopLayout", Q_ARG(int, orientation), Q_ARG(int, x), Q_ARG(int, y));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setDesktopLayout(orientation, x, y);
}

void KWinAdaptor::setOpacity(int winId, int opacityPercent)
{
    // handle method call org.kde.kwin.KWin.setOpacity
    QMetaObject::invokeMethod(parent(), "setOpacity", Q_ARG(int, winId), Q_ARG(int, opacityPercent));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setOpacity(winId, opacityPercent);
}

void KWinAdaptor::setShadowSize(int winId, int shadowSizePercent)
{
    // handle method call org.kde.kwin.KWin.setShadowSize
    QMetaObject::invokeMethod(parent(), "setShadowSize", Q_ARG(int, winId), Q_ARG(int, shadowSizePercent));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setShadowSize(winId, shadowSizePercent);
}

void KWinAdaptor::setUnshadowed(int winId)
{
    // handle method call org.kde.kwin.KWin.setUnshadowed
    QMetaObject::invokeMethod(parent(), "setUnshadowed", Q_ARG(int, winId));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setUnshadowed(winId);
}

void KWinAdaptor::showWindowMenuAt(int winId, int x, int y)
{
    // handle method call org.kde.kwin.KWin.showWindowMenuAt
    QMetaObject::invokeMethod(parent(), "showWindowMenuAt", Q_ARG(int, winId), Q_ARG(int, x), Q_ARG(int, y));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->showWindowMenuAt(winId, x, y);
}

void KWinAdaptor::startKompmgr()
{
    // handle method call org.kde.kwin.KWin.startKompmgr
    QMetaObject::invokeMethod(parent(), "startKompmgr");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->startKompmgr();
}

void KWinAdaptor::stopKompmgr()
{
    // handle method call org.kde.kwin.KWin.stopKompmgr
    QMetaObject::invokeMethod(parent(), "stopKompmgr");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->stopKompmgr();
}

void KWinAdaptor::unclutterDesktop()
{
    // handle method call org.kde.kwin.KWin.unclutterDesktop
    QMetaObject::invokeMethod(parent(), "unclutterDesktop");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->unclutterDesktop();
}


#include "kwinadaptor.moc"
