# SPDX-FileCopyrightText: 2026 Tobias Ozór <tobiasozor@outlook.com>
#
# SPDX-License-Identifier: BSD-2-Clause

[General]
disableUnqualifiedAccess = "i18n,i18nc,i18nd,i18ndc,i18ncp,i18np,xi18nc,xi18ndc,kcm,KWinOptionsSettings"
