import QtQuick 2.15

QtObject
{
    property bool alpha
    property var frameId
    property rect bufferGeometry
    property var pos
    property size size
    property real x
    property real y
    property real width
    property real height
    property rect visibleRect
    property real opacity
    property int screen
    property var windowId
    property rect rect
    property var clientPos
    property size clientSize
    property string resourceName
    property string resourceClass
    property var windowRole
    property bool desktopWindow
    property bool dock
    property bool toolbar
    property bool menu
    property bool normalWindow
    property bool dialog
    property bool splash
    property bool utility
    property bool dropdownMenu
    property bool popupMenu
    property bool tooltip
    property bool notification
    property bool criticalNotification
    property bool appletPopup
    property bool onScreenDisplay
    property bool comboBox
    property bool dndIcon
    property int windowType
    property bool managed
    property bool deleted
    property bool shaped
    property bool skipsCloseAnimation
    property var  surface
    property bool popupWindow
    property bool outline
    property var internalId
    property int pid
    property int stackingOrder
    property bool fullScreen
    property bool fullScreenable
    property bool active
    property int desktop
    property var desktops
    property bool onAllDesktops
    property var activities
    property var x11DesktopIds
    property bool skipTaskbar
    property bool skipPager
    property bool skipSwitcher
    property bool closeable
    property var /*QIcon*/ icon
    property bool keepAbove
    property bool keepBelow
    property bool shadeable
    property bool shade
    property bool minimizable
    property bool minimized
    property rect iconGeometry
    property bool specialWindow
    property bool demandsAttention
    property string caption
    property size minSize
    property size maxSize
    property bool wantsInput
    //property bool transient // this is a reserved word, so we skip it
    property var transientFor
    property bool modal
    property rect geometry
    property rect frameGeometry
    property bool move
    property bool resize
    property bool decorationHasAlpha
    property bool noBorder
    property bool providesContextHelp
    property bool maximizable
    property bool moveable
    property bool moveableAcrossScreens
    property bool resizeable
    property var desktopFileName
    property bool hasApplicationMenu
    property bool applicationMenuActive
    property bool unresponsive
    property string colorScheme
    property int layer
    property bool hidden
    property size basicUnit
    property bool blocksCompositing
    property bool clientSideDecorated
}
