/* This file contains all the paths that change when changing the installation prefix */

#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"

/* The compiled in system configuration prefix */
#define KDESYSCONFDIR "${SYSCONF_INSTALL_DIR}"

#define __KDE_BINDIR "${BIN_INSTALL_DIR}"

/* Compile in the exec prefix to help kstddirs in finding dynamic libs
   (This was for exec_prefix != prefix - still needed?) */
#define __KDE_EXECPREFIX "NONE"

#define LIBEXEC_INSTALL_DIR "${LIBEXEC_INSTALL_DIR}"
#define DATA_INSTALL_DIR "${DATA_INSTALL_DIR}"
#define LIB_INSTALL_DIR "${LIB_INSTALL_DIR}"
#define INCLUDE_INSTALL_DIR "${INCLUDE_INSTALL_DIR}"
#define BIN_INSTALL_DIR "${BIN_INSTALL_DIR}"
#define CONFIG_INSTALL_DIR "${CONFIG_INSTALL_DIR}"
#define HTML_INSTALL_DIR "${HTML_INSTALL_DIR}"
#define ICON_INSTALL_DIR "${ICON_INSTALL_DIR}"
#define KCFG_INSTALL_DIR "${KCFG_INSTALL_DIR}"
#define PLUGIN_INSTALL_DIR "${PLUGIN_INSTALL_DIR}"
#define SERVICES_INSTALL_DIR "${SERVICES_INSTALL_DIR}"
#define SERVICETYPES_INSTALL_DIR "${SERVICETYPES_INSTALL_DIR}"
#define SOUND_INSTALL_DIR "${SOUND_INSTALL_DIR}"
#define TEMPLATES_INSTALL_DIR "${TEMPLATES_INSTALL_DIR}"
#define WALLPAPER_INSTALL_DIR "${WALLPAPER_INSTALL_DIR}"
#define XDG_APPS_INSTALL_DIR "${XDG_APPS_INSTALL_DIR}"
#define XDG_DIRECTORY_INSTALL_DIR "${XDG_DIRECTORY_INSTALL_DIR}"
#define EXEC_INSTALL_PREFIX "${EXEC_INSTALL_PREFIX}"
#define SYSCONF_INSTALL_DIR "${SYSCONF_INSTALL_DIR}"
#define LOCALE_INSTALL_DIR "${LOCALE_INSTALL_DIR}"
#define SYSCONF_INSTALL_DIR "${SYSCONF_INSTALL_DIR}"
